# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ambulance_pb2 as ambulance__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ambulance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AmbulanceServiceStub(object):
    """AmbulanceService handles all inter-node gRPC communication:
    - Bully Algorithm election messages
    - Coordinator heartbeats
    - Ambulance dispatch orders
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendElection = channel.unary_unary(
                '/ambulance.AmbulanceService/SendElection',
                request_serializer=ambulance__pb2.ElectionMessage.SerializeToString,
                response_deserializer=ambulance__pb2.ElectionResponse.FromString,
                _registered_method=True)
        self.AnnounceCoordinator = channel.unary_unary(
                '/ambulance.AmbulanceService/AnnounceCoordinator',
                request_serializer=ambulance__pb2.CoordinatorMessage.SerializeToString,
                response_deserializer=ambulance__pb2.CoordinatorResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/ambulance.AmbulanceService/Heartbeat',
                request_serializer=ambulance__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=ambulance__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Dispatch = channel.unary_unary(
                '/ambulance.AmbulanceService/Dispatch',
                request_serializer=ambulance__pb2.DispatchRequest.SerializeToString,
                response_deserializer=ambulance__pb2.DispatchResponse.FromString,
                _registered_method=True)


class AmbulanceServiceServicer(object):
    """AmbulanceService handles all inter-node gRPC communication:
    - Bully Algorithm election messages
    - Coordinator heartbeats
    - Ambulance dispatch orders
    """

    def SendElection(self, request, context):
        """Sent by a node initiating an election to all nodes with higher IDs.
        A higher-ID node responds with OK and starts its own election.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnounceCoordinator(self, request, context):
        """Broadcast by the winning node to announce itself as the new coordinator.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Periodic ping sent by the coordinator so followers know it is alive.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dispatch(self, request, context):
        """Sent by the coordinator to the chosen ambulance, ordering it to respond.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AmbulanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendElection': grpc.unary_unary_rpc_method_handler(
                    servicer.SendElection,
                    request_deserializer=ambulance__pb2.ElectionMessage.FromString,
                    response_serializer=ambulance__pb2.ElectionResponse.SerializeToString,
            ),
            'AnnounceCoordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceCoordinator,
                    request_deserializer=ambulance__pb2.CoordinatorMessage.FromString,
                    response_serializer=ambulance__pb2.CoordinatorResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=ambulance__pb2.HeartbeatRequest.FromString,
                    response_serializer=ambulance__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Dispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.Dispatch,
                    request_deserializer=ambulance__pb2.DispatchRequest.FromString,
                    response_serializer=ambulance__pb2.DispatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ambulance.AmbulanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ambulance.AmbulanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AmbulanceService(object):
    """AmbulanceService handles all inter-node gRPC communication:
    - Bully Algorithm election messages
    - Coordinator heartbeats
    - Ambulance dispatch orders
    """

    @staticmethod
    def SendElection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ambulance.AmbulanceService/SendElection',
            ambulance__pb2.ElectionMessage.SerializeToString,
            ambulance__pb2.ElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnnounceCoordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ambulance.AmbulanceService/AnnounceCoordinator',
            ambulance__pb2.CoordinatorMessage.SerializeToString,
            ambulance__pb2.CoordinatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ambulance.AmbulanceService/Heartbeat',
            ambulance__pb2.HeartbeatRequest.SerializeToString,
            ambulance__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ambulance.AmbulanceService/Dispatch',
            ambulance__pb2.DispatchRequest.SerializeToString,
            ambulance__pb2.DispatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
