# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ambulance.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61mbulance.proto\x12\tambulance\"$\n\x0f\x45lectionMessage\x12\x11\n\tsender_id\x18\x01 \x01(\x05\"\"\n\x10\x45lectionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\",\n\x12\x43oordinatorMessage\x12\x16\n\x0e\x63oordinator_id\x18\x01 \x01(\x05\"%\n\x13\x43oordinatorResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"%\n\x10HeartbeatRequest\x12\x11\n\tsender_id\x18\x01 \x01(\x05\"#\n\x11HeartbeatResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"Q\n\x0f\x44ispatchRequest\x12\x14\n\x0cpatient_name\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x16\n\x0e\x63oordinator_id\x18\x03 \x01(\x05\"\"\n\x10\x44ispatchResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xbe\x02\n\x10\x41mbulanceService\x12G\n\x0cSendElection\x12\x1a.ambulance.ElectionMessage\x1a\x1b.ambulance.ElectionResponse\x12T\n\x13\x41nnounceCoordinator\x12\x1d.ambulance.CoordinatorMessage\x1a\x1e.ambulance.CoordinatorResponse\x12\x46\n\tHeartbeat\x12\x1b.ambulance.HeartbeatRequest\x1a\x1c.ambulance.HeartbeatResponse\x12\x43\n\x08\x44ispatch\x12\x1a.ambulance.DispatchRequest\x1a\x1b.ambulance.DispatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ambulance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONMESSAGE']._serialized_start=30
  _globals['_ELECTIONMESSAGE']._serialized_end=66
  _globals['_ELECTIONRESPONSE']._serialized_start=68
  _globals['_ELECTIONRESPONSE']._serialized_end=102
  _globals['_COORDINATORMESSAGE']._serialized_start=104
  _globals['_COORDINATORMESSAGE']._serialized_end=148
  _globals['_COORDINATORRESPONSE']._serialized_start=150
  _globals['_COORDINATORRESPONSE']._serialized_end=187
  _globals['_HEARTBEATREQUEST']._serialized_start=189
  _globals['_HEARTBEATREQUEST']._serialized_end=226
  _globals['_HEARTBEATRESPONSE']._serialized_start=228
  _globals['_HEARTBEATRESPONSE']._serialized_end=263
  _globals['_DISPATCHREQUEST']._serialized_start=265
  _globals['_DISPATCHREQUEST']._serialized_end=346
  _globals['_DISPATCHRESPONSE']._serialized_start=348
  _globals['_DISPATCHRESPONSE']._serialized_end=382
  _globals['_AMBULANCESERVICE']._serialized_start=385
  _globals['_AMBULANCESERVICE']._serialized_end=703
# @@protoc_insertion_point(module_scope)
